CREATE DATABASE GRADEDB;
USE GRADEDB;

CREATE TABLE ENGLISH (
  STUDENTNO INT(10),
  STUDENTNAME VARCHAR(20),
  SCORE INT
);

GRANT ALL PRIVILEGES ON GRADEDB.*
  TO root@localhost IDENTIFIED BY 'Root_0000';

INSERT INTO ENGLISH VALUES(1001,'ñÏìcâpóY',70);
INSERT INTO ENGLISH VALUES(1002,'ç‚ä_ëæèï',25);
INSERT INTO ENGLISH VALUES(1003,'à‰ì°Ç–ÇÎÇµ',90);
INSERT INTO ENGLISH VALUES(1004,'îÛìcïSót',45);
INSERT INTO ENGLISH VALUES(1005,'ïüçËò_ãg',70);
